# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["Keith Kurson <keith@glitch.com>"]
description = "DIOS death metal band page"
language = "javascript"
manifest_version = 3
name = "diosdeath.backend"
service_id = "JOtdhBNr65RJsVmhzkbH30"

[local_server]

  [local_server.kv_stores]

    [local_server.kv_stores.website-content]
      file = "./static-publisher/kvstore.json"
      format = "json"

[scripts]
  build = "npm run build"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.website-content]
